language: cpp

compiler:
  - gcc

install:
  - sudo add-apt-repository --yes ppa:boost-latest/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-filesystem1.54-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
