sudo: required
dist: trusty

language: cpp

env:
  global:
   - secure: "H1ZVbraqi9LAmdGM9O9VhFHJP6Uk1Ux2iZSQqmSUi+Ph4muk8vsr7Grqu6yPJOI71aSs73ugTxW3S6nYVzgB+nCqEHZk5RnjyDHDfvDAg0h+OsBP4u0dQ6IZMfFRhw6R8B+VpUKD4j687MLs3eUFMsRJ8/t+24+/T097dKYWij4="

matrix:
  include:
    - compiler: gcc
      env: TASK="lint"
    - compiler: gcc
      env: TASK="test-gcc"

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install python
  - sudo pip install cpplint
  - sudo apt-get -y install build-essential cmake git libgtk2.0-dev pkg-config python-dev python-numpy
  - sudo apt-get -y install libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev libtbb2
  - sudo apt-get -y install libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
  - sudo apt-get -y install unzip
  - wget https://www.dropbox.com/s/hbiqqutpzf4pf4b/opencv3.zip?dl=0
  - mv opencv3.zip?dl=0 opencv.zip
  - unzip opencv.zip
  - sudo cp opencv/* /usr/local/lib/
  - sudo /bin/bash -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
  - sudo ldconfig

script:
  - bash .travis.sh

after_success:
  - if [ "$TASK" == "coverage" ]; then bash <(curl -s https://codecov.io/bash); fi;
