language: cpp

matrix:
  include:
    - compiler: clang
      env: TASK="build"
    - compiler: gcc
      env: TASK="build"
    - compiler: clang
      env: TASK="test"

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository --yes ppa:boost-latest/ppa
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq cmake
  - sudo apt-get install -qq libboost-filesystem1.54-dev
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  
  #OpenCV 3
  - sudo apt-get install -qq build-essential
  - sudo apt-get install -qq cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
  - sudo apt-get install -qq python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev  
  - curl -sL https://github.com/Itseez/opencv/archive/3.0.0-beta.zip > opencv.zip
  - unzip opencv.zip
  - cd opencv-3.0.0-beta  
  - mkdir build
  - cd build  
  - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D WITH_QT=ON -D WITH_OPENGL=ON ..  
  - make -j4
  - sudo make install  
  - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'  
  - sudo ldconfig
  - echo "OpenCV installed."
  - cd ../../

script:
  - bash .travis.sh
