language: cpp

env:
  - OpenCV_INCLUDE_DIR=/home/travis/build/rbkloss/opencv/include 
  global:
   - secure: "H1ZVbraqi9LAmdGM9O9VhFHJP6Uk1Ux2iZSQqmSUi+Ph4muk8vsr7Grqu6yPJOI71aSs73ugTxW3S6nYVzgB+nCqEHZk5RnjyDHDfvDAg0h+OsBP4u0dQ6IZMfFRhw6R8B+VpUKD4j687MLs3eUFMsRJ8/t+24+/T097dKYWij4="

matrix:
  include:
    - compiler: clang
      env: TASK="build"
    - compiler: gcc
      env: TASK="test"
    - compiler: gcc
      env: TASK="coverage"

addons:
  coverity_scan:
    project:
      name: "rbkloss/ssf"
      description: "Build submitted via Travis CI"
    notification_email: rbk@dcc.ufmg.br
    build_command_prepend: "mkdir build; cd build; cmake -DBUILD_TESTS=ON .."
    build_command:   "make"
    branch_pattern: coverity_scan  

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository --yes ppa:boost-latest/ppa
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo add-apt-repository --yes ppa:kubuntu-ppa/backports
  - sudo apt-get update -qq
install:
  # OpenCV v3.0.0 (beta) install code (modified from orignal source: https://github.com/jayrambhia/Install-OpenCV)

  # OpenCV dependencies - Details available at: http://docs.opencv.org/trunk/doc/tutorials/introduction/linux_install/linux_install.html
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
  - sudo apt-get install -y python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
  - sudo apt-get install -qq cmake
  - sudo apt-get install -qq libboost-filesystem1.54-dev libboost-log1.54-dev libboost-date-time1.54-dev libboost-thread1.54-dev
  - sudo apt-get install build-essential
  - sudo apt-get install git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
  - sudo apt-get install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 90 

  # Download v3.0.0 .zip file and extract.
  - curl -sL https://github.com/Itseez/opencv/archive/3.0.0.zip > opencv.zip
  - unzip opencv.zip
  - cd opencv-3.0.0
  
  # Create a new 'build' folder.
  - mkdir build
  - cd build
  
  # Set build instructions for Ubuntu distro.
  - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D WITH_OPENGL=ON ..
  
  # Run 'make' with four threads.
  - make -j1
  
  # Install to OS.
  - sudo make install
  
  # Add configuration to OpenCV to tell it where the library files are located on the file system (/usr/local/lib)
  - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
  
  - sudo ldconfig
  - echo "OpenCV installed."
  
  # We need to return to the repo "root" folder, so we can then 'cd' into the C++ project folder.
  - cd ../../

script:


script:
  - [project_dir]
  - cmake .
  - make
  - ./[application_name] [params]
  - bash .travis.sh

  
after_success:
  - if [ "$TASK" == "coverage" ]; then bash <(curl -s https://codecov.io/bash); fi;

#http://answers.opencv.org/question/21977/best-way-to-depend-on-opencv-master-in-a-travis-ci-build-bot-instance/
#  https://gist.github.com/cgddrd/9d397fda0d72fe617c0e