version: 1.0.{build}

clone_folder: c:\ssiglib\

branches:
  # whitelist
  only:
    - development
    - appVeyor


os: Visual Studio 2013
platform: x64
configuration: Release

before_build:
  - mkdir build
  - cd build
  - "c:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64
  - cmake -DBUILD_TESTS=ON -DENABLE_COVERAGE=ON .. -G "Visual Studio 12 Win64"

build:
  verbosity: minimal
  parallel: true             
  project: ALL_BUILD.vcxproj 

init:
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=c:\ssiglib\opencv\build\ -D WITH_TBB=OFF -D WITH_FFMPEG=OFF -D WITH_V4L=OFF -D WITH_OPENMP=OFF -D BUILD_opencv_apps=OFF -D BUILD_DOCS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF -D BUILD_WITH_DEBUG_INFO=OFF .. -G "Visual Studio 12 Win64"
  - "c:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64
  - msbuild ALL_BUILD.vcxproj /p:configuration=release /p:platform=x64 /p:UseEnv=true /p:PreferredToolArchitecture=x64 /p:PlatformToolset=v120
  - setx -m OPENCV_BIN cc:\ssiglib\opencv\build\bin\Release\
  - setx -m OPENCV_DIR c:\ssiglib\opencv\build\

notifications:

  # Email
  - provider: Email
    to:
      - rbk@dcc.ufmg.br
    subject: 'Build {{status}}'                  
    message: "{{message}}, {{commitId}}, ..."    
    on_build_status_changed: true
